# Node CircleCI 2.0 configuration
#
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    docker:
      - image: circleci/node:lts-alpine
        environment:
          NODE_ENV: test
    steps:
      - checkout

      # Restore the dependency cache
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run: yarn install --frozen-lockfile

      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      # run tests!
      - run:
          name: Run Jest tests
          command: yarn test:ci
          environment:
            JEST_JUNIT_OUTPUT: 'reports/junit/js-test-results.xml'

      - run: yarn check-types

      # Save test results
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

      # CodeCov
      - codecov/upload:
          file: ./coverage/clover.xml
